"""Versioned public contract for forecheck.

Nothing outside this package may define a wire type. Modules import the enums and
models from here so that a contract change is a single, reviewable diff.
"""

from __future__ import annotations

from forecheck.contracts.context import (
    ActionContext,
    AffectedResource,
    AgentIdentity,
    Destination,
    Environment,
    FinancialExposure,
    Observation,
    PolicyStatement,
    Principal,
    ProposedAction,
    TrajectoryStep,
    UserObjective,
)
from forecheck.contracts.enums import (
    META_DIMENSIONS,
    MUTATING_OPERATIONS,
    SENSITIVITY_ORDER,
    AbstentionReason,
    AuthMethod,
    CalibrationMethod,
    Decision,
    DestinationRelationship,
    ErrorCode,
    FeedbackOutcome,
    LabelValue,
    ObligationKind,
    OperationKind,
    PrincipalType,
    ResourceKind,
    RiskDimension,
    RuleKind,
    Sensitivity,
    Stage,
    ToolFamily,
    TrustLevel,
)
from forecheck.contracts.errors import ErrorBody, ErrorResponse, ForecheckError
from forecheck.contracts.io import (
    SCHEMA_VERSION,
    BatchClassifyRequest,
    BatchClassifyResponse,
    CalibrationInfo,
    ClassifyOptions,
    ClassifyRequest,
    ClassifyResponse,
    DimensionScore,
    FeedbackAck,
    FeedbackRecord,
    ModelInfo,
    Obligation,
    PolicyDecision,
    PolicyEvaluateRequest,
    RuleMatch,
    TruncationInfo,
)
from forecheck.contracts.latent import (
    ATTACK_SEQUENCE_PATTERNS,
    ActionOrigin,
    AuthorizationBasis,
    ContextGap,
    DifficultyTier,
    LatentScenario,
    PolicyPredicate,
    PolicyPredicateKind,
    SequencePattern,
    ToolSpec,
)
from forecheck.contracts.limits import Limits
from forecheck.contracts.records import (
    INVARIANT_AXES,
    LABEL_SCHEMA_VERSION,
    ContrastiveAxis,
    DatasetManifest,
    Example,
    LabelSet,
    Provenance,
    SourceLicense,
    Split,
    Transformation,
    UsageRestriction,
)

__all__ = [
    "ATTACK_SEQUENCE_PATTERNS",
    "INVARIANT_AXES",
    "LABEL_SCHEMA_VERSION",
    "META_DIMENSIONS",
    "MUTATING_OPERATIONS",
    "SCHEMA_VERSION",
    "SENSITIVITY_ORDER",
    "AbstentionReason",
    "ActionContext",
    "ActionOrigin",
    "AffectedResource",
    "AgentIdentity",
    "AuthMethod",
    "AuthorizationBasis",
    "BatchClassifyRequest",
    "BatchClassifyResponse",
    "CalibrationInfo",
    "CalibrationMethod",
    "ClassifyOptions",
    "ClassifyRequest",
    "ClassifyResponse",
    "ContextGap",
    "ContrastiveAxis",
    "DatasetManifest",
    "Decision",
    "Destination",
    "DestinationRelationship",
    "DifficultyTier",
    "DimensionScore",
    "Environment",
    "ErrorBody",
    "ErrorCode",
    "ErrorResponse",
    "Example",
    "FeedbackAck",
    "FeedbackOutcome",
    "FeedbackRecord",
    "FinancialExposure",
    "ForecheckError",
    "LabelSet",
    "LabelValue",
    "LatentScenario",
    "Limits",
    "ModelInfo",
    "Obligation",
    "ObligationKind",
    "Observation",
    "OperationKind",
    "PolicyDecision",
    "PolicyEvaluateRequest",
    "PolicyPredicate",
    "PolicyPredicateKind",
    "PolicyStatement",
    "Principal",
    "PrincipalType",
    "ProposedAction",
    "Provenance",
    "ResourceKind",
    "RiskDimension",
    "RuleKind",
    "RuleMatch",
    "Sensitivity",
    "SequencePattern",
    "SourceLicense",
    "Split",
    "Stage",
    "ToolFamily",
    "ToolSpec",
    "TrajectoryStep",
    "Transformation",
    "TruncationInfo",
    "TrustLevel",
    "UsageRestriction",
    "UserObjective",
]
